# Generated by Django 5.2.17 on 2026-09-26 10:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiln', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpurityAssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampledOn', models.DateField(verbose_name='抽检日')),
                ('impurityPct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='杂质百分数(%)')),
                ('passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('chemistName', models.CharField(max_length=80, verbose_name='化验人')),
                ('voidedAt', models.DateTimeField(blank=True, null=True, verbose_name='作废时间')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assays_created', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assays', to='kiln.resinlot', verbose_name='来脂批')),
                ('voidedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assays_voided', to=settings.AUTH_USER_MODEL, verbose_name='作废人')),
            ],
            options={
                'verbose_name': '杂质抽检',
                'verbose_name_plural': '杂质抽检',
                'ordering': ['-sampledOn', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('voidedAt__isnull', True)), fields=('lot', 'sampledOn'), name='uniq_active_assay_per_lot_day')],
            },
        ),
    ]
